name: NonDex Flaky Test Check

on:
  push:
    branches: ["fix-flaky", "main"]
  workflow_dispatch:

jobs:
  run-nondex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Build project and dependencies
        run: mvn clean install -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am -DskipTests

      - name: Run NonDex on specific test
        run: mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl edu.illinois:nondex-maven-plugin:2.2.1:nondex -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testAddSubprocessToCaseWithStage
